### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by DutchmanNL** [Nafaya/esphome-native-api#5]
hi, thanks for this great library !

I tried to implement it into my application, having the issue if a device is not reachable the code crash with error below 👍 

```
unhandled promise rejection: connect EHOSTUNREACH 192.168.10.62:6053
(1931) Error: connect EHOSTUNREACH 192.168.10.62:6053 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
Exception-Code: EHOSTUNREACH: connect EHOSTUNREACH 192.168.10.62:6053
```

Not sure if its caused by the lib or the way I call the Code, can you give me a hint?

**Comment by Nafaya** [comment]
Hi, I can suppose some `EventEmmiter`'s `error` event is not handled. Since `error` event is special(if there is no callback added - `EventEmmiter` throws an unhandled error) and every class in this library extends `EventEmmiter` - you should add callbacks to Client, Connection or any Entity class:
```
client.on('error', console.error)
// or
connection.on('error', console.error)
// or
light.on('error', console.error)
// etc
```

Also it is common that `error` event is incapsulated and propagates from inner objects. So generally you have to add the callback to only one object.
*I just realized that errors are not propates from entities to client object. So I gonna add it tomorrow.

If this fairy tail does not help you, please, share a minimalistic reprodative code.

**Comment by DutchmanNL** [comment]
> *I just realized that errors are not propates from entities to client object. So I gonna add it tomorrow.

thank you, lets see if that does the trick indeed it happens in the entities part

**Comment by DutchmanNL** [comment]
oh what a shame ... Indeed relooked my code and forgot to have the .on('error') implemented causing the error.
Lets say that .... more coffee is needed at some moments

Thank you for you help and great module !
